name: Deploy

on:
  push:
    branches:
      - heroku-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vigorous" 
          heroku_email: "pirrefixus@gmail.com"
          usedocker: true